### ISSUE TITLE
Issues after update to 4.*

### ISSUE THREAD

**Issue by Svisstack** [DarkWanderer/ClickHouse.Client#100]
Hi Team,

We updated the library from 3.* to 4.* and immediately got errors like below while selecting more than 50k rows, the error occurring randomly only on 4.* version of the library. 

This is a known issue?

`  Message: 
Test method BBXT.Common.Values.Database.Tests.ValuesPersistenceRepositoryTests.InsertLargeDataThread threw exception: 
ClickHouse.Client.ClickHouseServerException: Code: 49, e.displayText() = DB::Exception: Block structure mismatch in Pipe::unitePipes stream: different number of columns:
and(greaterOrEquals(time, CAST('1635075168.000', 'DateTime64(3)')), less(time, CAST('1635247968.000', 'DateTime64(3)'))) UInt8 UInt8(size = 0), time DateTime64(9) DateTime64(size = 0), dim_id UInt64 UInt64(size = 0), value Float64 Float64(size = 0)
time DateTime64(9) DateTime64(size = 0), dim_id UInt64 UInt64(size = 0), value Float64 Float64(size = 0) (version 21.8.10.19 (official build))`

**Comment by DarkWanderer** [comment]
Assuming resolved as no feedback

**Comment by Svisstack** [comment]
Sorry, we downgraded do 3.* and will wait a little bit more with 4.*

**Comment by DarkWanderer** [comment]
Ok - if you discover any other issues, please let me know. The error with `BulkCopy` was fixed under #98 in v4.0.1
