### ISSUE TITLE
В какой момент закрывается соединение?

### ISSUE THREAD

**Issue by madaraice** [DarkWanderer/ClickHouse.Client#109]
Привет!
В какой момент закрывается соединение к БД? Ради интереса смотрел `ConnectionState` после вызова `Dispose()` и `ConnectionState` оставался в статусе `Open`, только после вызова `_connection.Close()` соединение закрывалось (`ConnectionState ` переходил в статус `Close`). Подскажите, так и должно быть? Может под капотом есть пул соединений и руками не нужно ничего закрывать?(вызывать `_connection.Close()`, например, в моей `ConnectionFactory`)

**Comment by DarkWanderer** [comment]
Привет.

Управление соединениями идёт через `HttpClient`, который держит пул соединений самостоятельно (при посредничестве `HttpClientHandler`). Вызов `Close()` необязателен, он только устанавливает флаг состояния в `Closed`. Соединения .NET Framework закроет сам, по истечению внутреннего таймаута. Если количество соединений - проблема, лучше всего использовать статический `HttpClient` или конструктор, который принимает `IHttpClientFactory`

**Comment by DarkWanderer** [comment]
В wiki есть статья на эту тему: https://github.com/DarkWanderer/ClickHouse.Client/wiki/Connection-lifetime-&-pooling

**Comment by madaraice** [comment]
Спасибо за ответ!
