### ISSUE TITLE
FixedString type

### ISSUE THREAD

**Issue by ridicoulous** [DarkWanderer/ClickHouse.Client#110]
Hello

According to the [docs](https://clickhouse.com/docs/en/sql-reference/data-types/fixedstring/), FixedString data type is useful to store hashes: 
`Binary representation of hashes (FixedString(16) for MD5, FixedString(32) for SHA256).`
But string representation of SHA256 takes 64 bytes instead of 32 bytes after insert. 
So it will be useful to have the ability to insert `byte[]` or `Span<byte>` into FixedType columns

**Comment by ridicoulous** [comment]
I assume it would be something like  this:
```cs
 public override void Write(ExtendedBinaryWriter writer, object value)
        {
           if (value is byte[])
            {
                writer.Write((byte[])value);
                return;
            }
            var @string = Convert.ToString(value, CultureInfo.InvariantCulture);
            var stringBytes = new byte[Length];
            Encoding.UTF8.GetBytes(@string, 0, @string.Length, stringBytes, 0);
            writer.Write(stringBytes);
        }
```
But not sure about formatting:
```cs 

                case StringType st:
                case FixedStringType tt:
                case Enum8Type e8t:
                case Enum16Type e16t:
                case IPv4Type ip4:
                case IPv6Type ip6:
                case UuidType uuidType:
                    return value.ToString();
```

**Comment by DarkWanderer** [comment]
Hi @ridicoulous 

This is a tricky request. ClickHouse parameterized queries use HTTP URL parameters, which inherently need to be representable by strings. The only place where binary representation is used directly is in `BulkCopy` mechanism - which is a separate way of insertion. When reading query results, the mapping from ClickHouse type to .NET type is direct & unconditional - if the type is `FixedString`, I can't return `string` or `byte[]` based on what was returned from database.

In theory, I can add a shortcut as described above (so `FixedString` and `String` types can write byte arrays if passed), but one would not be able to read those values back without using `base64Encode` or similar function - and parameterized queries (e.g. `SELECT * FROM tableWithHashes WHERE hash = {parameter:FixedString(32)}`) will still not work. Another downside is that an extra `if` and type check will eat performance on large volumes of data

Is it possible to work around this, e.g. by using a materialized view?
```sql
CREATE TABLE table (..., hash FixedString(16), hash_str FixedString(16) ALIAS base64Encode(hash))

CREATE MATERIALIZED VIEW mv_table_insert (..., hash_str FixedString(32), hash FixedString(16) MATERIALIZED base64Decode(hash_str)) TO table
```
Something like this should allow you to insert string values into `mv_table_insert`, they will be stored as binary values in `table` automatically

**Comment by DarkWanderer** [comment]
Another thought: can you use `Array(Byte)` type instead? While slightly less efficient (extra byte with length prefix), this will correctly translate to `byte[]` in `ClickHouse.Client`

**Comment by ridicoulous** [comment]
Thank you for responses. Array(Byte) sounds good, I'll try

**Comment by DarkWanderer** [comment]
Closing for now - please reoen or comment if the question is still actual
