### ISSUE TITLE
Add a link to Wiki documentation to README

### ISSUE THREAD

**Issue by pkese** [DarkWanderer/ClickHouse.Client#111]
If I wouldn't *accidentally* click on [bulk insertion](https://github.com/DarkWanderer/ClickHouse.Client/wiki/Bulk-insertion) link in README,  
I wouldn't know that there's some excellent documentation available for this project.

Please expose a big explicit link to the Wiki somewhere in README so that people can find it.

----

Also your About section refers to http://clickhouse.tech:
![image](https://user-images.githubusercontent.com/278492/146816375-27482a4d-c007-441e-b29d-a71a84d93e9a.png)
This makes it unclear whether you are the official clickhouse.tech dotnet client or you just happened to put a link to clickhouse there.

Whichever it is, it would be nice if you would make it specific.

**Comment by DarkWanderer** [comment]
Thanks for feedback - changes implemented
