### ISSUE TITLE
Add Bool to data type.

### ISSUE THREAD

**Issue by mbtolou** [DarkWanderer/ClickHouse.Client#113]
Hi.

ClickHouse add bool data type to database .

https://github.com/ClickHouse/ClickHouse/blob/1dcd3f9403dfe990f994891e24ed9618e562947d/tests/queries/0_stateless/02152_bool_type.sql

https://github.com/ClickHouse/ClickHouse/blob/1dcd3f9403dfe990f994891e24ed9618e562947d/tests/queries/0_stateless/02114_bool_type.sql

**Comment by DarkWanderer** [comment]
Thanks for heads-up, will be up in next release. Please note that `true` and `false` evaluate to `UInt8` at the moment (seems to be hardcoded in ClickHouse itself). Use `CAST(1, 'Bool')` to get a correct `Bool` value in expressions
