### ISSUE TITLE
"Overflow exception" for decimal types with big precision

### ISSUE THREAD

**Issue by Stan0v** [DarkWanderer/ClickHouse.Client#125]
DecimalType.cs has code to calculate 'Exponent' in 'Scale' setter => 
```
/// <summary>
/// Gets or sets the decimal 'scale' (precision) in ClickHouse
/// </summary>
public int Scale
{
    get => scale;
    set
    {
        scale = value;
        Exponent = MathUtils.ToPower(10, value);
    }
}
```
'Exponent' designed for storage of multiplexer and takes the result of raising the number 10 to a power of 'Scale' value =>
```     
/// <summary>
/// Gets decimal exponent value based on Scale
/// </summary>
public long Exponent { get; private set; }
```
In case of presence columns with Decimal type with 'Precision' above 30 approx. we ~~catch an overflow exception~~ silently recieve value flipped over the bound of long type which provides corrupted resulting data within database.

To fix this we need to change =>
```
/// <summary>
/// Gets decimal exponent value based on Scale
/// </summary>
public ulong Exponent { get; private set; }
```
in DecimalType.cs
And 'ToPower' function
```
public static ulong ToPower(int value, int power)
{
    ulong result = 1;
    ulong poweredValue = (ulong)value;

    while (power > 0)
    {
        if ((power & 1) == 1)
        {
            result *= poweredValue;
        }

        power >>= 1;
        if (power <= 0)
        {
            break;
        }

        poweredValue *= poweredValue;
    }
    return result;
}
```
within Utility\MathUtils.cs

**Comment by DarkWanderer** [comment]
Good day
`long` vs. `ulong` gives only 2 times difference - i.e. allows to have exponent of 10¹⁹ instead of 10¹⁸. That's not going to help if you have decimals with precision of 30

In addition to that, C#'s `decimal` allows precision only down to 10⁻²⁸ - so 10⁻³⁰ is simply unrepresentable in .NET.

What is your use case? Are there alternative ways you can achieve it?

**Comment by DarkWanderer** [comment]
Checked - there's nothing really stopping us from using `decimal` as an `Exponent` type instead of `long`/`ulong`. Will be in next release

**Comment by Stan0v** [comment]
Appreciate it

**Comment by DarkWanderer** [comment]
Fixed in latest release
