### ISSUE TITLE
Date32 values prior to 1970-01-01 cannot be read

### ISSUE THREAD

**Issue by MaceWindu** [DarkWanderer/ClickHouse.Client#136]
Dates before 1970-1-1 doesn't work because they read as uint instead of int:
![image](https://user-images.githubusercontent.com/1099238/176644983-ea34fe01-970a-4b8b-a6ea-bf2e1a463ee1.png)

_Originally posted by @MaceWindu in https://github.com/DarkWanderer/ClickHouse.Client/issues/130#issuecomment-1170994393_

**Comment by DarkWanderer** [comment]
Fixed in 4.3.1. Still does not go below 1st Jan 1925 (looks like ClickHouse limitation)
