### ISSUE TITLE
Support for big decimals

### ISSUE THREAD

**Issue by MaceWindu** [DarkWanderer/ClickHouse.Client#137]
Currently only `decimal` type supported, which doesn't allow to work with values with precision bigger than 28.

Possible options:
- `string`
- custom type
- `BigInteger` without exponent information
- `BigInteger` + scale tuple
- `BigInteger` + `BigInteger` exponent tuple

I don't have strong preferences, as I'm not using those types and ClickHouse in general, but I think support should include `string` plus some other option from list.

error example
```
System.OverflowException
  Message=Value was either too large or too small for a Decimal.
  Source=System.Runtime.Numerics
  StackTrace:
   at System.Numerics.BigInteger.op_Explicit(BigInteger value)
   at ClickHouse.Client.Types.DecimalType.Read(ExtendedBinaryReader reader)
   at ClickHouse.Client.ADO.Readers.ClickHouseDataReader.Read()
```

**Comment by DarkWanderer** [comment]
The problem with this is that decimals are inherently non-integer, and making decimals larger than specific value a different type will hurt consistency. Once support for wide integers is added, you can always use `toInt128`/`toInt256` function to convert the value to BigInteger (and it will capture the fact that you do an explicit conversion better(

**Comment by DarkWanderer** [comment]
Support for 'wide' decimal types was added in version 6.0.0
