### ISSUE TITLE
session_id support

### ISSUE THREAD

**Issue by DarkWanderer** [DarkWanderer/ClickHouse.Client#15]
> Similarly, you can use ClickHouse sessions in the HTTP protocol. To do this, you need to add the session_id GET parameter to the request. You can use any string as the session ID. By default, the session is terminated after 60 seconds of inactivity. To change this timeout, modify the default_session_timeout setting in the server configuration, or add the session_timeout GET parameter to the request. To check the session status, use the session_check=1 parameter. Only one query at a time can be executed within a single session.

**Comment by DarkWanderer** [comment]
TODO: add connstring parameter to tweak session timeout

**Comment by mbtolou** [comment]
custom session_id not supported yet.
please add this feature

thanks

**Comment by DarkWanderer** [comment]
Released in [1.1.0.197](https://github.com/DarkWanderer/ClickHouse.Client/releases/tag/1.1.0.197)
