### ISSUE TITLE
How to get client statistics with query results

### ISSUE THREAD

**Issue by yusufozturk** [DarkWanderer/ClickHouse.Client#175]
First of all, thank you for this library.

We would like to get client statistics with query results like:

 "statistics":
    {
        "elapsed": 0.000256913,
        "rows_read": 0,
        "bytes_read": 0
    }

so we can show query details like how much time it took on Clickhouse, how much GB of data it processed etc.
It will be a perfect details for the end users so they can realize how much impact their query creates.

Thanks.

**Comment by yusufozturk** [comment]
For reference:
https://github.com/ClickHouse/clickhouse-go/issues/639

Thanks.

**Comment by DarkWanderer** [comment]
See `ClickHouseCommand.QueryStats` field in version 5.1.1
