### ISSUE TITLE
Unknown type: Point on bulkcopy

### ISSUE THREAD

**Issue by arianpotter** [DarkWanderer/ClickHouse.Client#180]
Hi
I have a table with a column which its data type is point (geo type). when I want to bulk insert to my table using object array I get exception : 'Unknown type: Point'. is it because of not supporting geo types or something else?
thanks

**Comment by DarkWanderer** [comment]
Yes, I have not merged support for Geo types - #84 - yet

**Comment by DarkWanderer** [comment]
Basic Geo types have been enabled in `5.0.4` - let me know if that improves the situation

**Comment by DarkWanderer** [comment]
Please reopen if issue still occurs with latest version
