### ISSUE TITLE
Add Linq To DB to list of supported ORMs

### ISSUE THREAD

**Issue by MaceWindu** [DarkWanderer/ClickHouse.Client#189]
Could you please add [Linq To DB](https://github.com/linq2db/linq2db) to list of suppored ORMs [here](https://github.com/DarkWanderer/ClickHouse.Client/wiki/ORM-support) (wiki editing is not available to users outside of organisation)? Or even better add such information to project readme.

**Comment by DarkWanderer** [comment]
Added to both, thanks for suggestion
