### ISSUE TITLE
how to remove ClickHouseDecimal from dapper ?

### ISSUE THREAD

**Issue by mbtolou** [DarkWanderer/ClickHouse.Client#223]
Hello
I don't want decimal values to be handled by dapper.
How can I write or read data in the database without converting decimal to clickhousedecimal?

**Comment by DarkWanderer** [comment]
What doesn't work with dapper? Basic test case with querying `decimal` works:
```
        string sql = "SELECT toDecimal128(0.0001, 8)";
        var result = (await connection.QueryAsync<decimal>(sql)).Single();
        Assert.IsInstanceOf<decimal>(result);
        Assert.AreEqual(0.0001m, result);
```

**Comment by mbtolou** [comment]
![image](https://user-images.githubusercontent.com/6413705/199644450-ffc4005b-15c7-4ef8-9d5b-670e102cc4f0.png)

```csharp
var connection = AppConfig.GetChConn();
ClickHouseBulkCopy bulk = new ClickHouseBulkCopy(connection);
List<object[]> objs = new();
objs.Add(new object[] { DateTime.Now, 1, (decimal)123.03154648 });
bulk.DestinationTableName = "test.test_decimal";
var task = bulk.WriteToServerAsync(objs);
task.Wait();
```

```sql
CREATE TABLE
    test.test_decimal (
        `clock` DateTime64 ,
        `id` Int32,
        `value` Decimal(18, 5)
    ) ENGINE = MergeTree
ORDER BY
    clock SETTINGS index_granularity = 8192
```

**Comment by mbtolou** [comment]
In the previous versions, I did the same thing and no problem arose for me.
It was faster in terms of efficiency.

`csharp
var sw = Stopwatch.StartNew();
List<ClickHouseDecimal> click_dec = new();
for (decimal i = 0; i < 10000000; i += (decimal)0.25)
{
	click_dec.Add(i);
}
sw.Stop();
Console.WriteLine($"Add Performance ClickHouseDecimal: {sw.ElapsedMilliseconds}");

sw = Stopwatch.StartNew();
List<decimal> _decimal = new();
for (decimal i = 0; i < 10000000; i += (decimal)0.25)
{
	_decimal.Add(i);
}
sw.Stop();
Console.WriteLine($"Add Performance Decimal: {sw.ElapsedMilliseconds}");
`

![image](https://user-images.githubusercontent.com/6413705/199645919-3cab7ac2-21ac-45ad-9d58-131a62821f46.png)

**Comment by DarkWanderer** [comment]
Ok, fair enough. I have started work on adding an option to revert to `decimal` but it needed more polish, so it didn't get into 6.0 release - will try to include into next one

**Comment by mbtolou** [comment]
hi.

Can you implement the requested feature?

**Comment by DarkWanderer** [comment]
Added ability to use `UseCustomDecimals=false` flag in 6.4.0 for read side
