### ISSUE TITLE
Decimals read regression in v6

### ISSUE THREAD

**Issue by MaceWindu** [DarkWanderer/ClickHouse.Client#229]
It looks like big decimals support introduced two regressions.

test code

```cs
using var cn = new ClickHouseConnection("...");
cn.Open();
using var cmd = cn.CreateCommand();
// 7922816251426433759.3543950335 is decimal.MaxValue with scale=10
cmd.CommandText = "select toDecimal128('7922816251426433759.3543950335', 10)";
using var rd = cmd.ExecuteReader();
rd.Read();
```

First issue is that `GetDecimal` method doesn't handle `ClickHouseDecimal` instances:
```cs
// Unable to cast object of type 'ClickHouse.Client.Numerics.ClickHouseDecimal' to type 'System.Decimal'.
rd.GetDecimal(0);
```

Second issue is loss of precision when `ClickHouseDecimal` converted to `decimal`:
```cs
// contains proper value: 7922816251426433759.3543950335
var chDec = (ClickHouseDecimal)rd.GetValue(0);
// contains 7922816251426433759.354395033M - last digit lost
var dec = chDec.ToDecimal(CultureInfo.InvariantCulture);
```

**Comment by DarkWanderer** [comment]
First one is pretty embarassing - it should have been in the code coverage

Both issues should be fixed in [6.2.0](https://github.com/DarkWanderer/ClickHouse.Client/releases/tag/6.2.0)

**Comment by MaceWindu** [comment]
Can confirm it is fixed with one small issue. decimal conversion operator could fail [here](https://github.com/DarkWanderer/ClickHouse.Client/blob/master/ClickHouse.Client/Numerics/ClickHouseDecimal.cs#L192) for some values. E.g. for `toDecimal128('0', 29)`

**Comment by DarkWanderer** [comment]
This bit I unfortunately cannot fix - the exception comes from .NET Framework itself
