### ISSUE TITLE
NullReferenceException when using ClickHouseConnection constructor that accepts HttpClient

### ISSUE THREAD

**Issue by i-sinister** [DarkWanderer/ClickHouse.Client#23]
Calling ClickHouseConnection constructor that accepts both connection string and HttpClient instance in version 1.1.0.197 throws following exception:
> System.NullReferenceException : Object reference not set to an instance of an object.
>     Stack Trace:
>        at ClickHouse.Client.ADO.ClickHouseConnection.set_ConnectionString(String value)
>    at ClickHouse.Client.ADO.ClickHouseConnection..ctor(String connectionString, HttpClient httpClient)

This happens because constructor first sets ConnectionString property and then assigns httpClient field but ConnectionString property's setter sets Timeout on httpClient

**Comment by DarkWanderer** [comment]
Thank you for the report, rather silly error. Will push out fix with next release

**Comment by DarkWanderer** [comment]
Fix released, please reopen if reoccurs in latest version
