### ISSUE TITLE
System.Text.Json and Microsoft.Extensions.Http dependency version

### ISSUE THREAD

**Issue by MaceWindu** [DarkWanderer/ClickHouse.Client#238]
I see that `System.Text.Json` dependency version was bumped to 7.0.0. While I don't have issue with it personally and know it will work with all supported tfms, still it probably makes sense to downgrade it for `net5.0`/`netcoreapp3.1` targets to 6.0.7 if there is no compatibility issues to avoid build warnings like that on build for library consumers:
```
System.Text.Json 7.0.0 doesn't support net5.0 and has not been tested with it. Consider upgrading your TargetFramework to net6.0 or later. You may also set <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings> in the project file to ignore this warning and attempt to run in this unsupported configuration at your own risk.
```

Use of `SuppressTfmSupportBuildWarnings` is safe for this specific case but it could also hide real versioning issues with other nugets (e.g. could throw `PlatformNotSupportedException` when used with unsupported TFM)

**Comment by MaceWindu** [comment]
Same issue is for Microsoft.Extensions.Http 7.0.0

**Comment by DarkWanderer** [comment]
Will take a look, thanks for highlighting
