### ISSUE TITLE
Invalid (nullable) datetime handling in 1.1.0.197

### ISSUE THREAD

**Issue by i-sinister** [DarkWanderer/ClickHouse.Client#24]
I have an table with non-nullable datetime column. When I try to read results of the following query when table is empty:
```sql
select max(accesstime) as accesstime from access_log
```
following exception is thrown:
> Exception has occurred: CLR/System.InvalidCastException
> Exception thrown: 'System.InvalidCastException' in ClickHouse.Client.dll: 'Unable to cast object of type 'System.String' to type 'System.DateTime'.'
>    at ClickHouse.Client.ADO.Readers.ClickHouseDataReader.GetDateTime(Int32 ordinal)

`GetDateTime` is called because `reader.IsDBNull()` returns `false`. CH response (compact json):
```json
{
	"meta":
	[
		{
			"name": "accesstime",
			"type": "DateTime"
		}
	],

	"data":
	[
		["0000-00-00 00:00:00"]
	],

	"rows": 1,

	"statistics":
	{
		"elapsed": 0.00023376,
		"rows_read": 0,
		"bytes_read": 0
	}
}
```

Changing query to following:
```sql
select maxOrNull(accesstime) as accesstime from access_log
```
results in different exception:
> Exception has occurred: CLR/System.InvalidCastException
> Exception thrown: 'System.InvalidCastException' in System.Private.CoreLib.dll: 'Unable to cast object of type 'System.DBNull' to type 'System.String'.'
>    at ClickHouse.Client.ADO.Readers.ClickHouseJsonCompactReader.TryConvertTo(Object data, ClickHouseType type)
>    at ClickHouse.Client.ADO.Readers.ClickHouseJsonCompactReader.TryConvertTo(Object data, ClickHouseType type)
>    at ClickHouse.Client.ADO.Readers.ClickHouseJsonCompactReader.Read()
>    at System.Data.Common.DbDataReader.ReadAsync(CancellationToken cancellationToken)
CH response (compact json):
```json
{
	"meta":
	[
		{
			"name": "accesstime",
			"type": "Nullable(DateTime)"
		}
	],

	"data":
	[
		[null]
	],

	"rows": 1,

	"statistics":
	{
		"elapsed": 0.000256913,
		"rows_read": 0,
		"bytes_read": 0
	}
}
```

**Comment by DarkWanderer** [comment]
Can you try same using Binary protocol in connection string?

**Comment by DarkWanderer** [comment]
The first issue is due to `0000-00-00 00:00:00` not being recognized as valid DateTime, so the Json converter left it as a string.
Second issue is a bug due to DBNull not being recognized correctly.

I've pushed fixed for both into `master`, will release tomorrow. However in any case I recommend using `Binary` protocol, as it's much more robust (and JSON/TSV will be deprecated soon)

**Comment by DarkWanderer** [comment]
Fix released, please reopen if reoccurs in latest version
