### ISSUE TITLE
The return value of ExecuteNonQuery is always 0

### ISSUE THREAD

**Issue by d4ilys** [DarkWanderer/ClickHouse.Client#249]
Hello, I noticed that ExecuteNonQuery is an Int return value, but it is always 0, and I can't tell whether the modification or deletion was successful based on it.
Is there any good way to do this?

**Comment by DarkWanderer** [comment]
Greetings. Do you mean `ALTER TABLE DELETE` and/or `ALTER TABLE UPDATE`? These are async and execute in background, so ClickHouse does not return any information about them inside the query - even in stats:
```json
{"read_rows":"0","read_bytes":"0","written_rows":"0","written_bytes":"0","total_rows_to_read":"0","result_rows":"0","result_bytes":"0"}
```
I don't know of a way to source this information - let me know if you find one

For `INSERT` statements, there is `ClickHouseCommand.QueryStats` field
