### ISSUE TITLE
ALTER TABLE DELETE

### ISSUE THREAD

**Issue by mbtolou** [DarkWanderer/ClickHouse.Client#25]
Hi,

who can i execute alter query ? 
ALETR TABLE TABLE1 DELETE WHERE ....

**Comment by mbtolou** [comment]
i check query
query work correctly. but run async  with fast response.

in special scenario, duplicate data generated.

**Comment by DarkWanderer** [comment]
What do you mean, duplicate data? This is `ALTER TABLE .... DELETE` query, how can it produce duplicate data? Do you have an example?

**Comment by mbtolou** [comment]
I'm sorry.

for example : 
first delete 100000 record .
then insert new record with order key ,

in first step(delete 100000 record)  `await connection.ExecuteStatementAsync` response very fast , 
if call `Thread.Sleep(10000)` and then insert new data , new data replace correctly in the table ,
but if remove  `Thread.Sleep(10000)`  ,new data add to exiting data and data duplicated.

**Comment by hohaftf** [comment]
I guess it's clickhouse server behavior. Check the [docs](https://clickhouse.tech/docs/en/sql_reference/statements/alter/#alter-mutations)

> A mutation query returns immediately after the mutation entry is added (in case of replicated tables to ZooKeeper, for nonreplicated tables - to the filesystem). The mutation itself executes asynchronously using the system profile settings.

> For *MergeTree tables mutations execute by rewriting whole data parts. There is no atomicity - parts are substituted for mutated parts as soon as they are ready and a SELECT query that started executing during a mutation will see data from parts that have already been mutated along with data from parts that have not been mutated yet.
