### ISSUE TITLE
[Question] But how can I pass parameters? 

### ISSUE THREAD

**Issue by t-smirnov** [DarkWanderer/ClickHouse.Client#26]
Could you explain here with little example or add to readme, please?

**Comment by DarkWanderer** [comment]
Hi, passing parameters is something I had half-ready but forgot to finalize. I'll add it to next release

The syntax is as follows:
```
            using var command = connection.CreateCommand();
            command.CommandText = "SELECT {id:Int32}, {str:String}, {tuple:Tuple(UInt8, String)}";
            
            command.AddParameter("id", 906324);
            command.AddParameter("str", "Any string, even with some unicode");
            command.AddParameter("tuple", "(10, 'str')");

            var result = await command.ExecuteReaderAsync();
```
This uses ClickHouse's

`AddParameter` is an extension to do `command.AddParameter(); parameter.Value = ...` etc.

**Comment by t-smirnov** [comment]
Oh, nice, thanks @DarkWanderer
