### ISSUE TITLE
How to configure timeout

### ISSUE THREAD

**Issue by michel4liu** [DarkWanderer/ClickHouse.Client#264]
hi

Whether configuration is supported   connect_timeout、receive_timeout、send_timeout 

https://clickhouse.com/docs/zh/operations/settings/settings/#connect-timeout-receive-timeout-send-timeout

**Comment by DarkWanderer** [comment]
Hi,

You can add custom parameters to connection string with `set_` prefix:
```
Host=myhost;Username=user;set_connect_timeout=123
```
and it will be passed to ClickHouse. Note however that ClickHouse may ignore some settings passed this way as when URL is parsed, TCP and HTTP contexts are already initialized using server-side values
