### ISSUE TITLE
DbDataReader does not have GetFieldValues method

### ISSUE THREAD

**Issue by FreePhoenix888** [DarkWanderer/ClickHouse.Client#265]
https://github.com/DarkWanderer/ClickHouse.Client/wiki/Nested-columns-support#:~:text=var%20values%20%3D%20reader.GetFieldValues()%3B%20//%20First%20row

**Comment by FreePhoenix888** [comment]
@DarkWanderer

**Comment by DarkWanderer** [comment]
This is an internal extension method - removed from documentation, thanks

**Comment by FreePhoenix888** [comment]
@DarkWanderer , what should I use instead?

**Comment by DarkWanderer** [comment]
You can either:

1. Use a one-liner: `Enumerable.Range(0, reader.FieldCount).Select(reader.GetValue).ToArray();` (this is what that extension method did)
2. Use regular ADO.NET DbDataReader interface
3. Use extension defined in `ClickHouse.Client.Utility` namespace: `dataReader.AsEnumerable().Single()`

**Comment by FreePhoenix888** [comment]
> 3\. ClickHouse.Client.Utility

Are you sure about the 3rd variant?
![image](https://user-images.githubusercontent.com/66206278/218509338-6ca27b15-8e30-456e-9a29-b90d4398cc7b.png)
