### ISSUE TITLE
Is it possible to connect to local clickhouse by using this client like by using clickhouse-client cli application?

### ISSUE THREAD

**Issue by FreePhoenix888** [DarkWanderer/ClickHouse.Client#269]
Is it possible to connect to local clickhouse by using this client like by using clickhouse-client cli application?

**Comment by FreePhoenix888** [comment]
@DarkWanderer

**Comment by DarkWanderer** [comment]
No, this is a library, not a command-line tool

**Comment by FreePhoenix888** [comment]
> No, this is a library, not a command-line tool

Anyway even local instance of clickhouse open ports for using it and I just had to change url to the server url and it worked
