### ISSUE TITLE
Add option to send query as POST

### ISSUE THREAD

**Issue by tkirill** [DarkWanderer/ClickHouse.Client#270]
Hi!

I'm trying to send parameterized selects to ClickHouse and getting "414 Request-URI Too Large" from ClickHouse.

ClickHouse supports sending queries in a body of POST request. And it started ([issue](https://github.com/ClickHouse/ClickHouse/issues/8842)) to support sending query parameters in a request body recently.

What do you think about giving an option to send query as POST?

**Comment by DarkWanderer** [comment]
Hi,

This is something I wanted to implement a while ago but it wasn't supported back then, glad to see it was added server-side!

Will definitely take a look

**Comment by ArtemAstashkin** [comment]
Hi @DarkWanderer!

I've added the pull request which adds support of the feature, could you check it?

_Some tests don't work on version prior Aug 10, 2022_
