### ISSUE TITLE
I'm trying to connect to a ClickHouse database using ClickHouse.Client with the following connection

### ISSUE THREAD

**Issue by KawhiWei** [DarkWanderer/ClickHouse.Client#295]
![image](https://user-images.githubusercontent.com/46982191/232068857-afcc4285-1b30-44fb-bb88-5294a37d5f41.png)
However, I'm getting an error message saying "Port 9000 is for clickhouse-client program. You must use port 8123 for HTTP". This suggests that the ClickHouse server is not allowing connections on port 9000 for some reason.
《Host=192.168.31.20;Port=9000;User=kawhi;Password=wzw0126..;Database=luck_asa》
How can I correctly connect to ClickHouse using port 9000? Is there a specific configuration that needs to be changed on the server side, or do I need to modify my connection string in some way?

Thanks for your help!

**Comment by DarkWanderer** [comment]
Hi. ClickHouse supports multiple protocols. It uses port 9000 (by default) for "native" protocol - the one ClickHouse itself and some clients use. Unfortunately this client requires use of HTTP protocol, which is by default on port 8123
