### ISSUE TITLE
Server exceptions are buried by ClickHouseBulkCopy

### ISSUE THREAD

**Issue by smbecker** [DarkWanderer/ClickHouse.Client#321]
I was having issues where it seemed that `ClickHouseBulkCopy.WriteToServerAsync` was completing successfully and providing the number of rows written. However, the table in CH was still empty. I found that [this continuation](https://github.com/DarkWanderer/ClickHouse.Client/blob/master/ClickHouse.Client/Copy/ClickHouseBulkCopy.cs#L172) blindly ignores the exception that it thrown from `PostStreamAsync`.

**Comment by DarkWanderer** [comment]
Thank you for report, this is indeed a very annoying issue. Fix will be available in version 6.7.1
