### ISSUE TITLE
Wrong decimal serialization

### ISSUE THREAD

**Issue by pprogs** [DarkWanderer/ClickHouse.Client#33]
Привет!

В BinaryStreamWriter.cs
[https://github.com/DarkWanderer/ClickHouse.Client/blob/master/ClickHouse.Client/Formats/BinaryStreamWriter.cs#L61](url)

Не верно записывает отрицательные decimal значения (они становятся положительные и не верные)

Исправил по аналогии, как в нативной реализации
https://github.com/killwort/ClickHouse-Net/blob/master/ClickHouse.Ado/Impl/ColumnTypes/DecimalColumnType.cs#L52

Стало нормально.

**Comment by DarkWanderer** [comment]
Привет

https://github.com/killwort/ClickHouse-Net/blob/master/ClickHouse.Ado/Impl/ColumnTypes/DecimalColumnType.cs#L52 - это не нативная реализация, только копия :) Там кстати та же ошибка для `Decimal128`

Ошибку нашел, спасибо за репорт, исправлю

**Comment by DarkWanderer** [comment]
Пофикшено в релизе 1.3
