### ISSUE TITLE
Nullable DateTime

### ISSUE THREAD

**Issue by ierror** [DarkWanderer/ClickHouse.Client#366]
When i set an DateTime Column to null, i get this exception:

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=ClickHouse.Client
  StackTrace:
   at ClickHouse.Client.Types.DateTimeType.Write(ExtendedBinaryWriter writer, Object value) in D:\a\ClickHouse.Client\ClickHouse.Client\ClickHouse.Client\Types\DateTimeType.cs:line 29
```

Any idea how to solve? 

Thanks for your work, a great library!

**Comment by DarkWanderer** [comment]
Hi,

I'm pretty late to reply, but in case this is still relevant - ClickHouse is not like other databases in the sense that the types are much more strongly set. Unlike SQL Server or Oracle, if a column has type `Int32`, the only thing you can write there is a valid `Int32`. If you need to write `null` values, you need to set the column type to something which can accomodate `null` - specifically, `Nullable(DateTime)` - or have a special value which denotes `not set` (like `1970-01-01` - epoch start)
