### ISSUE TITLE
Query optimization suggestion

### ISSUE THREAD

**Issue by mbtolou** [DarkWanderer/ClickHouse.Client#376]
Hi.

Is there a solution that does not request the column information list for each insert in the database?
I suggest that it be sent as an argument to the function or cached as a variable in the class.

https://github.com/DarkWanderer/ClickHouse.Client/blob/53f2434bb3edc4fe2eae58820509ccba139f8123/ClickHouse.Client/Copy/ClickHouseBulkCopy.cs#L99

**Comment by DarkWanderer** [comment]
I've started working on this previously but shelved due to lack of time - thanks for reminding, I'll take a look in coming weeks

**Comment by DarkWanderer** [comment]
Added in version 6.8.0, please check and let me know in case of any issues

**Comment by mbtolou** [comment]
Before raising the problem, I thank you for your kindness.

I suggest you delete the current line so that if you don't know the list of columns, the class will automatically call the list of columns from the bank for the first time.

Thank

https://github.com/DarkWanderer/ClickHouse.Client/blob/096f5157ce59c974b221c5e84b6b58355cb6176a/ClickHouse.Client/Copy/ClickHouseBulkCopy.cs#L79C26-L79C26

**Comment by DarkWanderer** [comment]
Thank you for your suggestion - indeed, that's an easy opportunity for improvement. Added in 6.8.1

**Comment by mbtolou** [comment]
when use cache bulk copy class ,
 The `RowsWritten` value is reported incorrectly
