### ISSUE TITLE
ServerVersion strange value

### ISSUE THREAD

**Issue by DBalashov** [DarkWanderer/ClickHouse.Client#38]
Using last version Clickhouse.Client ( 2.0.0.262 ):

![20200702_220007](https://user-images.githubusercontent.com/2083946/86389300-8aab4400-bcaf-11ea-9e76-daf7f7bffacd.png)

Connection string: Host=192.168.0.113;Port=8123;Database=AGNET;User=default;Password=P@ssw0rd

select version(): 20.5.2.7

**Comment by DarkWanderer** [comment]
I see you are passing your own `HttpClient` instance, are you enabling decompression in it?

Default HttpClient has decompression enabled:
```
            var httpClientHandler = new HttpClientHandler() { AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate };
            httpClient = new HttpClient(httpClientHandler, true)
            {
                Timeout = timeout,
            };
```

**Comment by DBalashov** [comment]
thanks!
