### ISSUE TITLE
ClickHouseBulkCopy sends additional empty request if BatchSize equals to rows collection length

### ISSUE THREAD

**Issue by DmitryZhelnin** [DarkWanderer/ClickHouse.Client#403]
In this `while` cycle `hasMore` variable actually means that previous read was successful but not that there is more data to read.

https://github.com/DarkWanderer/ClickHouse.Client/blob/babcce5009669761b8b02311c5e9b358ef1ffdff/ClickHouse.Client/Copy/ClickHouseBulkCopy.cs#L176-L187

so when `BatchSize` equals to the size of provided collection new request with empty stream is created (in outer do/while loop) and sent to the server.

**Comment by DarkWanderer** [comment]
Hi. Thanks for report - looks like `ClickHouseBulkCopy` is due for a minor rewrite

**Comment by DarkWanderer** [comment]
Fixed in latest version
