### ISSUE TITLE
Insert data for nested type inside a nested type

### ISSUE THREAD

**Issue by jcast07** [DarkWanderer/ClickHouse.Client#413]
I am trying to insert data for a structure that contains a nested type in a nested type, the snippet below is just a sample
CREATE TABLE IF NOT EXISTS multiNested
(
    `id` UInt32,
    `params` Nested(param_id UInt8, param_val Nested(name String, description String))
)
ENGINE = MergeTree
PRIMARY KEY id

I have tried several approaches and no luck the approach below is the latest approach I have tried but get the following error.

Code: 33. DB::Exception: Cannot read all data. Bytes read: 85. Bytes expected: 118.: (at row 1)
: While executing BinaryRowInputFormat. (CANNOT_READ_ALL_DATA) (version 23.8.1.2759 (official build))

public static async Task InsertData()
{            
    using var connection = new ClickHouseConnection("Host =localhost;Protocol=http;Port=8123;Database=default");
    using var bulkCopy = new ClickHouseBulkCopy(connection) { DestinationTableName = "default.multiNested" };
    // Note again that technically the table has 2 columns, but we are preparing 3-column rows
    var row1 = new object[] { 1, new[] { 1, 2, 3 }, new[] { ("v1", "version 1"), ("v2", "version 2"), ("v3", "version 3") } };
    var row2 = new object[] { 2, new[] { 4, 5, 6 }, new[] { ("v4", "version 4"), ("v5", "version 5"), ("v6", "version 6") } };

    await bulkCopy.WriteToServerAsync(new[] { row1, row2 }, CancellationToken.None);
}

Is it possible to use the BulkCopy to perform inserts for nested types within nested types

**Comment by DarkWanderer** [comment]
This behavior should work correctly now if you add `flatten_nested=0` parameter to the connection (e.g. by using `set_flatten_nested=0` in connection string)
