### ISSUE TITLE
HTTP Connection leak under Linux

### ISSUE THREAD

**Issue by mineevks** [DarkWanderer/ClickHouse.Client#42]
Здравствуйте,
подскажите пожалуйста, я делаю bulkinsert (для простоты напрямую из MVC api контроллера)
```
       ClickHouseConnection connection = TestUtilities.GetTestClickHouseConnection();
        using (var bulkCopy = new ClickHouseBulkCopy(connection))
        {
            bulkCopy.DestinationTableName = "Test";
            await bulkCopy.WriteToServerAsync(objectsList.ToArray(), CancellationToken.None);
        };
```
Здесь TestUtilities это статический класс взятый из вашего примера.

Данные сохраняются в ClickHouse,
но в моем .Net Core 2.2 приложении накапливаются не закрытые коннекты.
Каждый вызов ClickHouseBulkCopy добавляет 1 незакрытый коннект.
После достижения лимита 30000 (в моем случае это пара дней) приложение аварийно закрывается.

Проблема существует если запускать из Ubuntu (контейнера).
Если запускать из Windows10, то незакрытых коннектов нет.

Количество открытых коннектов проверяю через:
```
long currentConnections = IPGlobalProperties.GetIPGlobalProperties()
                .GetTcpIPv4Statistics()
                .CurrentConnections;
```

Подскажите, что я делаю не так, можно ли этого избежать?

**Comment by mineevks** [comment]
Рост коннектов начинается в ClickHouseBulkCopy.cs  методе 
`public async Task WriteToServerAsync(IEnumerable<object[]> rows, IReadOnlyCollection<string> columns, CancellationToken token)`

сразу после вызова:
```
using (var reader = (ClickHouseDataReader)await connection.ExecuteReaderAsync($"SELECT {GetColumnsExpression(columns)} FROM {DestinationTableName} LIMIT 0"))
            {
                columnTypes = reader.GetClickHouseColumnTypes();
                columnNames ??= reader.GetColumnNames();
            }
```

**Comment by DarkWanderer** [comment]
Добрый день. Спасибо за репорт.

Смог воспроизвести, похоже что действительно есть leak где-то в BulkCopy. Я исправил утечку объектов в одном месте - не освобождался `HttpResponseMessage` в `PostBulkQueryAsync` после отправки данных (не совсем там где вы упомянули, но близко) - в новой версии `2.2.1.285`. Посмотрите, если поможет - если нет, буду тестировать подробнее

**Comment by mineevks** [comment]
Здравствуйте,
спасибо что ответили,
попробовал новую версию версии 2.2.1.285,  но у меня по прежнему рост коннекшенс.
Вот детали моего теста:

1) Пробую запускать из докер контейнера из ранчер:
При старте: currentConnections: 3
Далее при каждом обновлении увеличивается на 1.

2) Пробую запускать из докер контейнера локально:
При старте: currentConnections: 3-5
Далее при каждом обновлении увеличивается на 1.

3) Запускаю из Visual Studio:
При старте: currentConnections: 70
Далее при каждом обновлении меняется от 69 до 74, те не растет.

4) dotnet WSTest.dll
http://127.0.0.1:5090/test/clickhouse
При старте: currentConnections: 76
Далее при каждом обновлении меняется от 69 до 76-80, те не растет.


Архив своего примерчика выложил на google.drive
https://drive.google.com/file/d/14fXhcFByqsf1D7F9UDmdM_ZXRh-O2Nyb/view?usp=sharing

**Comment by DarkWanderer** [comment]
Посмотрел на код - так у вас же сами объекты `Connection` утекают. `TestController` создаётся на каждый запрос, в нём поле `private ClickHouseConnection _clickHouseConnection`, на которое никогда не делается `Dispose`. Попробуйте создавать `ClickHouseConnection` прямо в методе `ClickHouse` под `using`

В тестах я по этому поводу не заморачивался потому что тесты (хотя вообще стоит)

**Comment by mineevks** [comment]
Спасибо вам за помощь заработало! Сделал единственным вызов ClickHouseConnection connection = TestUtilities.GetTestClickHouseConnection();
при старте.

По поводу ClickHouseConnection с using, пробовал так, но коннекшены не закрываются.
            ```
            var builder = new ClickHouseConnectionStringBuilder
            {
                ConnectionString = _wSettings.ConnectionStrings.ClickHouseConnection,
                Compression = true
            };
            using (var clickHouseConnection = new ClickHouseConnection(builder.ConnectionString))
            {
                using (var bulkCopy = new ClickHouseBulkCopy(clickHouseConnection))
                {
                    bulkCopy.DestinationTableName = "Tasks";                    
                    await  bulkCopy.WriteToServerAsync(objectsArray, CancellationToken.None);
                };
            }
```

**Comment by ahmeturun** [comment]
umm.. I'm not sure about what is this case exactly about(auto translate is not so good on Russian), but it seems you're talking about bulk copy feature. can you check out this issue that I opened, it might be duplicate of this
https://github.com/DarkWanderer/ClickHouse.Client/issues/43.
thanks.

**Comment by DarkWanderer** [comment]
Related to `HttpClient` behavior, see https://github.com/DarkWanderer/ClickHouse.Client/wiki/Connection-lifetime-&-pooling
