### ISSUE TITLE
"DB::Exception: Session is locked by a concurrent" error on ClickHouseBulkCopy.WriteToServerAsync

### ISSUE THREAD

**Issue by ahmeturun** [DarkWanderer/ClickHouse.Client#43]
Hi,
so I've face the "clickhouse DB::Exception: Session is locked by a concurrent" exception when using the 'WriteToServerAsync' method. at first I thought it was a clickhouse error and well there was an existing issue on clickhouse which [isthis](https://github.com/ClickHouse/ClickHouse/issues/4003). 
But after further investigation I've come to realize that issue happens because the usage of the same clickhouse connection instance in parallel tasks [here](https://github.com/DarkWanderer/ClickHouse.Client/blob/5cfb0f680c58c6517132448a253eaba499483ca2/ClickHouse.Client/Copy/ClickHouseBulkCopy.cs#L116). the problem is that when the number of rows to be copied is like 10 or more times bigger that [BatchSize](https://github.com/DarkWanderer/ClickHouse.Client/blob/master/ClickHouse.Client/Copy/ClickHouseBulkCopy.cs#L31) then the same clickhouse connection is used with paralled uncompleted tasks, and that raises "DB::Exception: Session is locked by a concurrent" exception as it should.
instead of using the same connection, the bulk copy operation should have one connection per parallel task.

**Comment by DarkWanderer** [comment]
Hi,

If you are using `ClickHouseBulkCopy` with sessions enabled, you need to either set `MaxDegreeOfParallelism` to 1, or create a separate connection with sessions disabled. It's mentioned in the [docs](https://github.com/DarkWanderer/ClickHouse.Client/wiki/Bulk-insertion#notes). Not related to issue you've mentioned

**Comment by ahmeturun** [comment]
yeah, missed the docs there, thanks.
