### ISSUE TITLE
insert .. select from query with Kafka engine breaks down the server.

### ISSUE THREAD

**Issue by kayanme** [DarkWanderer/ClickHouse.Client#446]
I've put an issue in [Clickhouse github](https://github.com/ClickHouse/ClickHouse/issues/61060), but I think it should be replicated here.

In short (more words there)

Given the DB scheme
```SQL
create table default.insertlocal  (num UInt32) Engine=Null();

create table default.insertlocal2 as   default.insertlocal Engine=Memory();
create or replace table KafkaSend  as  default.insertlocal ENGINE = Kafka ('kafka:29092', 'topic', 'clickhouse') SETTINGS kafka_format = 'JSONEachRow';

create materialized view  default.KafkaLink to default.KafkaSend as select * from default.insertlocal;

insert into insertlocal2 select arrayJoin(range(100));
```

This query goes fine from the server, but crashes from Clickhouse Client 
`insert into  default.insertlocal select * from default.insertlocal2`

Version of CC is 7.1.1

**Comment by DarkWanderer** [comment]
Hi. This is interesting. 

Am I understanding correctly that this query specifically causes the crash?
```
insert into  default.insertlocal select * from default.insertlocal2
```
If so, I am not quite sure how it the client implementation can affect it as the query content will just be pushed as body of HTTP query

> This query goes fine from the server, but crashes from Clickhouse Client

Does this mean that this query works when executed from builtin clickhouise-client CLI?

**Comment by kayanme** [comment]
> Am I understanding correctly that this query specifically causes the crash?
Yes.

>Does this mean that this query works when executed from builtin clickhouise-client CLI?
And yes.

Actually I can't understand that too. We can also do a query without an intermediate table, just inserting some raw values from cli or from library - yet cli is ok, client is not.

A had some theories like some connection properties (tried all - no effect), async inserts and other asynchronicity (looks like the CH reserve some space in part for the data, but insert tht part before it has been actually filled) - something that could be at http connection and absent in binary, which cli uses.
Actually I didn't try the other clients.

**Comment by DarkWanderer** [comment]
I will close this for now as this seems to be a serverside issue
