### ISSUE TITLE
Large Tuple size not supported

### ISSUE THREAD

**Issue by OlegGavrilov** [DarkWanderer/ClickHouse.Client#46]
Large Tuple column (with more than 7 members) will fail object mapping to the underlying .NET Tuple<> type with an unexpected NRE on this line: 

https://github.com/DarkWanderer/ClickHouse.Client/blob/5cfb0f680c58c6517132448a253eaba499483ca2/ClickHouse.Client/Types/TupleType.cs#L34

Is it possible to fix this? Possibly use ...TRest of the biggest Tuple class or just deserialize as a string, when exception happens?

**Comment by OlegGavrilov** [comment]
Example: 
```c#
await using var connection = new ClickHouseConnection();
var c = connection.CreateCommand();
c.CommandText = "select (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)";
var r = await c.ExecuteScalarAsync(); // throws NRE
```

**Comment by DarkWanderer** [comment]
Fixed in [3.0](https://github.com/DarkWanderer/ClickHouse.Client/releases/tag/3.0.0.357) (might revisit later)

**Comment by daanmgneni** [comment]
switch to ValueTuple to support more than seven elements without nesting.

**Comment by DarkWanderer** [comment]
Can you clarify that? `ValueType` is still a generic with `<T1,T2,T3,T4,T5,T6,T7,TRest>` arguments: https://learn.microsoft.com/en-us/dotnet/api/system.valuetuple-8.-ctor?view=net-8.0
