### ISSUE TITLE
ClickHouseBulkCopy nested columns data is not written to the database

### ISSUE THREAD

**Issue by aleksandrkarpenko** [DarkWanderer/ClickHouse.Client#47]
When I tries to write data with latest version of library (2.2.2.294) I am getting exception:
`ClickHouse.Client.ClickHouseServerException (0x0000003E): Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 1 (line 1, col 1): ﻿INSERT INTO DatabaseName.TableName (col1, nested1.col1, nested1.col2) FORMAT RowBinary
?��^�k�?????�k�?????�g�?????Lg�?????��^�k�?????Lg�?????��^�k�?????�f�??. Unrecognized token (version 20.3.18.10 (official build))`
It is working with the previous version of library (2.1.0.269)

**Comment by DarkWanderer** [comment]
Might be a corner-case bug which crept in with latest change. What's the table schema, please?

**Comment by aleksandrkarpenko** [comment]
> Might be a corner-case bug which crept in with latest change. What's the table schema, please?

This is a creation script 
`CREATE TABLE IF NOT EXISTS DatabaseName.TableName
(
    time    DateTime,
    ticks Nested
    (
        ask Decimal64(7),
        bid Decimal64(7)
    )
) ENGINE = ReplacingMergeTree()
ORDER BY time`

**Comment by DarkWanderer** [comment]
Ah, it seems the new way of handling `BulkCopy` in 2.2.2 is only compatible with newer versions (`20.8.*`-ish) and not with older ones. Thanks for reporting - will fix

**Comment by aleksandrkarpenko** [comment]
> Ah, it seems the new way of handling `BulkCopy` in 2.2.2 is only compatible with newer ClickHouse versions (`20.8.*`-ish) and not with older ones. Thanks for reporting - will fix

thanks in advance

**Comment by DarkWanderer** [comment]
Closing, as has been properly fixed in `2.3.0`
