### ISSUE TITLE
handling of Nullable types. 

### ISSUE THREAD

**Issue by xfiodembo** [DarkWanderer/ClickHouse.Client#480]
I have an implementation that has a property of type 
`public DateTime? ANullableDateTime { get; set; }`

when this field has a value there are no issues however when it is null server sends this error. 
`<Error> DynamicQueryHandler: Code: 48. DB::Exception: Serialization is not implemented for type Nothing: value \N cannot be parsed as Nothing for query parameter 'ANullableDateTime': While executing ValuesBlockInputFormat. (NOT_IMPLEMENTED)`

error also seems to suggest '\N' is being passed as the value, 
`internal static class HttpParameterFormatter
{
    private const string NullValueString = "\\N";
...`

Im not clear whether this is a bug on the client or a gap on the db server with http/https . Shouldn't the type actually be Nullable(DateTime) based on doc here ?  https://clickhouse.com/docs/en/sql-reference/data-types/nullable

server version:  (version 24.4.1.2088 (official build))

**Comment by DarkWanderer** [comment]
Hi. `\\N` is a string representation as expected by ClickHouse server. When the type is specified in the query as `Nullable(something)`, `\\N` means a null value. There is however a quirk - while ClickHouse.Client has automatic type detection for cases where types were not provided, this detection is not perfect and cannot deduce the type of object based on `null`. For example, sending `INSERT INTO table 1 (my_value) VALUES ({my_value})` query with `null` does not give client enough information to understand that my_value is actually a `Nullable(string)`, and type `DbNull` is deduced.

If you can affect the SQL statement which are utilized in your case, specifying the type explicitly
`INSERT INTO table 1 (my_value) VALUES ({my_value:Nullable(String)})`

**Comment by xfiodembo** [comment]
I spoke with folks at clickhouse . Is there a way i can override this behavior ? I believe there is a bug . here is their response 
`
Code: 53. DB::Exception: Cannot convert string \\N to type Decimal(9, 2): While executing ValuesBlockInputFormat. (TYPE_MISMATCH) (version 24.4.1.2088 (official build))

****
  Today at 9:20 AM
When I replace Nullable(UInt32)  to Nullable(Decimal64(2))  it still works.
But in the exception message, it's ValuesBlockInputFormat, so it uses values format. In this case, it should use Null, e.g.
echo '(1), (Null), (2)' | curl "http://localhost:8123/?query=insert+into+tab+format+Values" --data-binary @-`

If i can override this and send null it may be worth a try.

**Comment by DarkWanderer** [comment]
Do you have a minimum reproducible example? It seems at the moment you are trying to insert a NULL value into a Decimal column, which doesn't work with ClickHouse

**Comment by DarkWanderer** [comment]
Do you have a minimum reproducible example for this?
