### ISSUE TITLE
Unable to create ClickHouse.Client.ADO.QueryStats (cannot convert to Int32)

### ISSUE THREAD

**Issue by TPCharts** [DarkWanderer/ClickHouse.Client#507]
I'm performing a query that returns the following response header:

```
{"read_rows":"37458913","read_bytes":"13948940818","written_rows":"0","written_bytes":"0","total_rows_to_read":"37458913","result_rows":"50","result_bytes":"85048","elapsed_ns":"4702022353"}
```

At ClickHouseHouseCommand.cs line 252, it throws an exception that it cannot parse an Int32 value.

```
private static QueryStats ExtractQueryStats(HttpResponseMessage response)
    {
        try
        {
            const string summaryHeader = "X-ClickHouse-Summary";
            if (response.Headers.Contains(summaryHeader))
            {
                var value = response.Headers.GetValues(summaryHeader).FirstOrDefault();
                
                // ⬇️ This line throws the error ⬇️
                var jsonDoc = JsonDocument.Parse(value); 
                
                return JsonSerializer.Deserialize<QueryStats>(value, SummarySerializerOptions);
            }
        }
        catch
        {
        }
        return null;
    }
```

These are the exception details:

```
System.Text.Json.JsonException
  HResult=0x80131500
  Message=The JSON value could not be converted to ClickHouse.Client.ADO.QueryStats. Path: $.read_bytes | LineNumber: 0 | BytePositionInLine: 50.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex) in /_/src/libraries/System.Text.Json/src/System/Text/Json/ThrowHelper.Serialization.cs:line 437

  This exception was originally thrown at this call stack:
    System.Text.Json.ThrowHelper.ThrowFormatException(System.Text.Json.NumericType) in ThrowHelper.cs
    System.Text.Json.Utf8JsonReader.GetInt32WithQuotes() in Utf8JsonReader.TryGet.cs
    System.Text.Json.Serialization.JsonConverter<T>.TryRead(ref System.Text.Json.Utf8JsonReader, System.Type, System.Text.Json.JsonSerializerOptions, ref System.Text.Json.ReadStack, out T, out bool) in JsonConverterOfT.cs
    System.Text.Json.Serialization.JsonConverter<T>.TryReadAsObject(ref System.Text.Json.Utf8JsonReader, System.Type, System.Text.Json.JsonSerializerOptions, ref System.Text.Json.ReadStack, out object) in JsonConverterOfT.cs
    System.Text.Json.Serialization.Converters.LargeObjectWithParameterizedConstructorConverter<T>.ReadAndCacheConstructorArgument(ref System.Text.Json.ReadStack, ref System.Text.Json.Utf8JsonReader, System.Text.Json.Serialization.Metadata.JsonParameterInfo) in ObjectWithParameterizedConstructorConverter.Large.cs
    System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter<T>.OnTryRead(ref System.Text.Json.Utf8JsonReader, System.Type, System.Text.Json.JsonSerializerOptions, ref System.Text.Json.ReadStack, out T) in ObjectWithParameterizedConstructorConverter.cs
    System.Text.Json.Serialization.JsonConverter<T>.TryRead(ref System.Text.Json.Utf8JsonReader, System.Type, System.Text.Json.JsonSerializerOptions, ref System.Text.Json.ReadStack, out T, out bool) in JsonConverterOfT.cs
    System.Text.Json.Serialization.JsonConverter<T>.ReadCore(ref System.Text.Json.Utf8JsonReader, System.Text.Json.JsonSerializerOptions, ref System.Text.Json.ReadStack) in JsonConverterOfT.ReadCore.cs

Inner Exception 1:
FormatException: Either the JSON value is not in a supported format, or is out of bounds for an Int32.
```

My guess is that, since Int32 is limited to 2,147,483,647, perhaps `"read_bytes":"13948940818"` is causing the problem. (However, I'm way over my head here!)

If the above guess is correct, then perhaps changing QueryStats to use long would solve the issue.

```
﻿namespace ClickHouse.Client.ADO;

#pragma warning disable SA1313 // Parameter names should begin with lower-case letter
public record class QueryStats(int ReadRows, int ReadBytes, int WrittenRows, int WrittenBytes, int TotalRowsToRead);
#pragma warning restore SA1313 // Parameter names should begin with lower-case letter
```

However, I'm skeptical that this is the real problem, since it seems like someone else would have encountered it already encountered it.

Any ideas for a possible workaround, or more information I could provide?

Thanks!

______

Quick update & solution:

1. Removed the ClickHouse.Client NuGet package
2. Cloned this repository's main branch and added reference to affected project.
3. Replaced QueryStats `int` argument types with `long`
4. This prevented the exception described above (but I'm unsure of possible negative side effects, or why nobody else encountered this - don't think my database or queries are significantly larger than what most ClickHouse users would be using).

```
public record class QueryStats(
    long ReadRows,
    long ReadBytes,
    long WrittenRows,
    long WrittenBytes,
    long TotalRowsToRead
);
```

**Comment by DarkWanderer** [comment]
Thanks for reporting - indeed, an easily fixable oversight. Should be fixed in v7.6.2

**Comment by MikeAmputer** [comment]
@DarkWanderer  Is there a reason why `QueryStats` does not contain some header fields: `result_rows`, `result_bytes`, and `elapsed_ns`?

**Comment by DarkWanderer** [comment]
The only reason would be that these fields were not present when I added this functionality. Feel free to contribute, should be a trivial change

**Comment by TPCharts** [comment]
Quick update on this:

I'm not sure if this actually solved the problem.

While running in Visual Studio with the debugger, I noticed an exception is actually being triggered at the line:

`return JsonSerializer.Deserialize<QueryStats>(value, SummarySerializerOptions);`

With the message:

`System.ArrayTypeMismatchException: 'Attempted to access an element as a type incompatible with the array.'`

 ```
   private static QueryStats ExtractQueryStats(HttpResponseMessage response)
    {
        try
        {
            const string summaryHeader = "X-ClickHouse-Summary";
            if (response.Headers.Contains(summaryHeader))
            {
                var value = response.Headers.GetValues(summaryHeader).FirstOrDefault();
                var jsonDoc = JsonDocument.Parse(value);
                
                // ⬇️⬇️ This line throws
                return JsonSerializer.Deserialize<QueryStats>(value, SummarySerializerOptions);
            }
        }
        catch
        {
              // ⚠️⚠️ Exceptions being swallowed here, only noticed when running debugger
        }
        return null;
    }
```

My guess is that `JsonSerializer.Deserialize` is struggling to convert some (all?) values to `long`. 

Setting all `QueryStats` arguments back to `int` stops this family of exceptions (but that will cause the same problems in some cases as the original post in this thread, so not really a solution).

The reason I didn't notice this issue originally is probably because the `try { } catch{ } ` block swallows the exception and returns null, so it's not visible unless running the debugger. 

The actual `value` `Json.Deserializer` is trying to parse in this case is:

`{"read_rows":"0","read_bytes":"0","written_rows":"0","written_bytes":"0","total_rows_to_read":"0","result_rows":"0","result_bytes":"0","elapsed_ns":"601293"}`

... with it throwing on other similar variations.

The query I'm executing is: 

```
await context.Database.ExecuteSqlRawAsync(
    $"DROP TABLE IF EXISTS {DatabaseNameSelected}.{tableName}"
);
```

... via EntityFramework using https://github.com/denis-ivanov/EntityFrameworkCore.ClickHouse (so I believe that's the exact query being used - no EF auto-magic happening to modify it as far as I know).


I'm not sure what happens if `QueryStats` returns null, or if that's significant in for this case. 

Is it probably OK to let the exception be swallowed if I'm just dropping tables?

Or, is there a better workaround? (I'm using a cloned version of the repository, so can try things out without needing a NuGet package update).

Thanks!
