### ISSUE TITLE
Aggregate function datatypes are not supported

### ISSUE THREAD

**Issue by fenjas** [DarkWanderer/ClickHouse.Client#51]
An exception is thrown when an AggregateFunction datatype is encountered.

![image](https://user-images.githubusercontent.com/19566745/100355274-c09bec80-2ff1-11eb-9788-3f25ad2a260c.png)
![image](https://user-images.githubusercontent.com/19566745/100355400-f9d45c80-2ff1-11eb-985a-5a5c8afc269d.png)

Will support for this datatype be available in upcoming releases?

**Comment by fenjas** [comment]
https://clickhouse.tech/docs/en/sql-reference/data-types/aggregatefunction/

**Comment by DarkWanderer** [comment]
Hi. `AggregateFunction` column does not make sense by itself - you can neither insert nor select data directly. It can only be handled with functions like `...State` for insertion and `...Merge` (e.g.: `uniqState`, `uniqMerge`). It's not possible to support it directly - you can't even get output for it from ClickHouse itself via JSON/TSV

To query `AggregatedFunction`-type column, you need to use a `...Merge` function. In this case the correct way to select would be:
`select <other fields>, argMaxMerge(device_group_name), argMaxMerge(transaction_country_alpha_2_code) from <table>`

**Comment by DarkWanderer** [comment]
Solidified this in [wiki](https://github.com/DarkWanderer/ClickHouse.Client/wiki/AggregateFunction) for future reference
