### ISSUE TITLE
ExecuteStatementAsync() not returning number of rows affected

### ISSUE THREAD

**Issue by nikkhn** [DarkWanderer/ClickHouse.Client#511]
When executing a successful `INSERT` statement with `ExecuteStatementAsync()` the number of rows affected is always coming back as 0. The INSERT statement is very simple, below:

<img width="1105" alt="Screenshot 2024-08-11 at 1 50 03 PM" src="https://github.com/user-attachments/assets/8c24963d-4eeb-4223-9bc0-d2c9b66c97ad">

 I've verified the insert is going in successfully. 

<img width="585" alt="Screenshot 2024-08-11 at 1 54 13 PM" src="https://github.com/user-attachments/assets/f8d2b92d-de16-40d0-b1a7-5db72e680236">

Wondering if im missing something with how `ExecuteStatementAsync()` should behave (as i see its a wrapper over ExecuteNonQueryAsync()`)

**Comment by MikeAmputer** [comment]
This library uses the HTTP interface of the ClickHouse server. According to the [official documentation](https://clickhouse.com/docs/en/interfaces/http):
```
For successful requests that do not return a data table, an empty response body is returned.
```
In some cases, you can use the `ClickHouseCommand.QueryStats` attribute to access `written_rows` metrics provided by the `X-ClickHouse-Summary` response header. This is particularly useful for `INSERT` statements, but note that it is set to `0` for `TRUNCATE` statements.

**Comment by MikeAmputer** [comment]
To be honest, I’m not entirely sure if the `ExecuteNonQueryAsync` implementation will ever return a non-zero value:
```c#
using var reader = new ExtendedBinaryReader(await response.Content.ReadAsStreamAsync().ConfigureAwait(false));
return reader.PeekChar() != -1 ? reader.Read7BitEncodedInt() : 0;
```
All the tests still pass (checked for 23.6) if I simplify this to `return 0;` =)

**Comment by nikkhn** [comment]
hm ok i misunderstood the client code then. I was looking at this [Connection Extensions method](https://github.com/DarkWanderer/ClickHouse.Client/blob/6b81e28e674ab7cbb803ad3f56a1712dc72409d3/ClickHouse.Client/Utility/ConnectionExtensions.cs#L10) and assumed it should be returning an integer?

**Comment by MikeAmputer** [comment]
Correct. The extension method you mentioned calls `command.ExecuteNonQueryAsync()`, which is the method I was referring to. To access `WrittenRows`, you'll need to create a command manually:
```c#
using var command = connection.CreateCommand();
command.CommandText = sql;
await command.ExecuteNonQueryAsync();
var writtenRows = command.QueryStats.WrittenRows;
```

**Comment by nikkhn** [comment]
AH i see, ok! thank you @MikeAmputer  :)
