### ISSUE TITLE
[FEAT] Implement query batching using DbBatch for fast query execution

### ISSUE THREAD

**Issue by Hermholtz** [DarkWanderer/ClickHouse.Client#545]
### Problem statement

Since .NET 6 there is a generic way to perform batched query execution in ADO.NET using the [DbBatch](https://learn.microsoft.com/en-us/dotnet/api/system.data.common.dbbatch) feature.  It allows for multiple queries to be ran in one round-trip to the server, sometimes providing astonishing speedups.

There are new methods in DbConnection - CreateBatch and CreateDbBatch, and the property CanCreateBatch to facilitate that. 

The following simple example shows how it works with PostgreSQL:

```csharp
using var connection = new NpgsqlConnection(builder.ConnectionString);
connection.Open();

using var batch = connection.CreateBatch();

for (int i = 0; i < 100; i++)
{
  batch.BatchCommands.Add(new NpgsqlBatchCommand($"insert into tab1 values ('row{i}')"));
}
batch.ExecuteNonQuery();
```

In my quick tests it averages 50.000 such inserts per second in a batch, versus 3.000 individual inserts using DbCommand - more than 16x speedup.

Below an example with parameters handled in a provider-agnostic way:

```csharp
using var batch = connection.CreateBatch();

for (int i = 0; i < 50000; i++)
{
	var batchCommand = batch.CreateBatchCommand();
	batchCommand.CommandText = $"insert into tab1 values (@val)";

	var parameter = batchCommand.CreateParameter();
	parameter.ParameterName = "@val";
	parameter.Value = $"row{i}";
	
	batchCommand.Parameters.Add(parameter);
	batch.BatchCommands.Add(batchCommand);
}
batch.ExecuteNonQuery();
```

This one is a barebone example how to use a single DataReader to get results from multiple batched queries (the NextResult is not a new feature):

```csharp
using var batch = connection.CreateBatch();

batch.BatchCommands.Add(new NpgsqlBatchCommand($"select 1 as a, 2 as b"));
batch.BatchCommands.Add(new NpgsqlBatchCommand($"select 1 as a, 2 as b, 3 as c"));
using var reader = batch.ExecuteReader();

do {
	while (reader.Read()) {
		var data = new List<string>();
		for (int col = 0; col < reader.FieldCount; col++) {
			string colName = reader.GetName(col);
			string value = reader.GetValue(col).ToString();
			data.Add($"{colName}: {value}");
		}
		Console.WriteLine(string.Join(", ", data));
	}
} while (reader.NextResult());
```

The feature is described in details in https://github.com/dotnet/runtime/issues/28633.

### Suggested solution

Please implement that feature when you have some time. As ClickHouse aims to be fast, data ingestion using C# also should be as fast as possible, and batching definitely helps with that.

### Considered alternatives

One can always fall back to using explicit transactions embracing multiple DbCommands. or concatenate multiple SQL queries into one string. But then it's more difficult to maintain parameters, and it is much easier to hit limits than with DbBatch.

**Comment by DarkWanderer** [comment]
Greetings

I agree, it would be a neat feature

Unfortunately to my knowledge ClickHouse does not support multiple queries via HTTP protocol, so it would not be possible to implement meaningfully. There is an open recent PR but the discussion is still open: https://github.com/ClickHouse/ClickHouse/issues/61608

See also: https://github.com/ClickHouse/ClickHouse/issues/6707

Closing for now, let's reopen when support is added
