### ISSUE TITLE
 DB::Exception: Unknown format RowBinaryWithNamesAndTypes

### ISSUE THREAD

**Issue by barsv** [DarkWanderer/ClickHouse.Client#59]
I was getting "DB::Exception: Unknown format RowBinaryWithNamesAndTypes" for the code in the quick start example.
The cause was in that the version of ClickHouse was 18.
As far as I understand RowBinaryWithNamesAndTypes is supported in ClickHouse starting from version 19.

I created this issue just for information for others.

**Comment by barsv** [comment]
I noticed that ClickHouse.Client gets version() on every connection opening. Probably it's better to add code to either throw an exception if the version is not supported or change the line 25 in master/ClickHouse.Client/ClickHouseUriBuilder.cs
`public string DefaultFormat => "RowBinaryWithNamesAndTypes";`
to something else.

**Comment by DarkWanderer** [comment]
Hi,

If you're stuck with older ClickHouse version, you can try 1.x versions of ClickHouse.Client, they have support for TabSeparated and JSON formats, which will allow to work with CH version 18 and earlier
