### ISSUE TITLE
Ensure Dapper support

### ISSUE THREAD

**Issue by DarkWanderer** [DarkWanderer/ClickHouse.Client#6]
- [x] Support basic queries
- [x] Support array parameters
- [x] Support array return type

**Comment by Ivasek** [comment]
Привет, небольшой фидбек про даппер. Попробовал подключить клиент в свой проект с даппером. Есть проблемы с QueryAsync - не удалось никак заставить работать (method not supported), синхронный вариант работает тоже не полностью (не поддерживается param). Обычный вариант Query<T> вроде заработал.

**Comment by DarkWanderer** [comment]
Приветствую. Похоже, в Async-версии Dapper вызывает `NextResultAsync` вместо `NextResult`. Добавил туда тоже `false`. В версии [1.0.0](https://www.nuget.org/packages/ClickHouse.Client/1.0.0.174) исправлено

**Comment by Treno1** [comment]
Глянул на параметры, есть две проблемы.
1) Даппер работает с параметрами с символом собаки (@). Пример из теста
```string sql = "SELECT * FROM system.table_functions WHERE name IN @Names";
var functions = (await connection.QueryAsync<string>(sql, new { Names = new string[] { "mysql", "odbc" } } )).ToList();```
Как итог, в клик улетает `SELECT * FROM system.table_functions WHERE name IN (@Names1,@Names2) FORMAT RowBinaryWithNamesAndTypes`

Ну и соответственно клик ругается на символ собаки `DB::Exception: Syntax error: failed at position 53: @Names1,@Names2`

Как вариант можно реплейсить @Names1 на {Names1:ТИП_ПЕРЕМЕННОЙ}, определять тип из ParametersCollection. Но там начнутся пляски с тем чтобы случайно собаку внутри строки не заменить.

Есть идеи получше или так попробовать?

**Comment by Treno1** [comment]
Вторая проблема не критична, но даппер разбил массив на несколько переменных. Можно проигнорить, но если массив оч большой то стрельнет

**Comment by DarkWanderer** [comment]
Вот как раз не хочется влезать в замену, потому что это выстрелит где-то в самом неожиданном месте. Я думал добавить ANTLR для парсинга SQL-запросов, если/когда руки дойдут, можно будет менять на уровне токенов.

Но - в принципе, после последних изменений Dapper с одним простым параметром [работает](https://github.com/DarkWanderer/ClickHouse.Client/blob/295c1c01bc26b43bf3fb42f6e1ded843c43dd6d2/ClickHouse.Client.Tests/ORM/DapperTests.cs#L25). С массивами проблема исключительно на стороне Dapper - он считает что база не поддерживает массивы. Я поднял [PR](https://github.com/StackExchange/Dapper/pull/1462), как только его смерджат, проблема должна уйти, при использовании новой версии Dapper.

Можно посмотреть в сторону добавления тестов для других типов (по `TestUtilities.GetDataTypeSamples()`), чтобы понять где ещё могут быть проблемы кроме массивов

**Comment by ridicoulous** [comment]
Hello, @DarkWanderer 
I got `System.IO.EndOfStreamException: 'Unable to read beyond the end of the stream.'` inside Dapper internal `SqlMapper.Async.cs` file when try to execute query with parameters [described here](https://github.com/DarkWanderer/ClickHouse.Client/blob/295c1c01bc26b43bf3fb42f6e1ded843c43dd6d2/ClickHouse.Client.Tests/ORM/DapperTests.cs#L25): ClickHouse version is  `20.9.2.20`. As you can see, query was successfully executed and data returned, but, presumably, Dapper's DbDataReader didn't see end of stream in my ClickHouse version. Does you have any ideas?
![dapper](https://user-images.githubusercontent.com/5917631/95220577-4922bb80-07ff-11eb-9b03-7d6328e3c1af.png)

**Comment by DarkWanderer** [comment]
Hi @ridicoulous, does this exception propagate outside of ClickHouse.Client internal function? `EndOfStreamException` can be created and caught during normal work (I'll fix that in some future version). If you skip it, everything should work correctly, e.g.:
```
using Dapper;
<.....>
            string sql = "SELECT * FROM system.numbers LIMIT 10";
            var integers = (await connection.QueryAsync<int>(sql)).ToList();
```

**Comment by ridicoulous** [comment]
Hi @DarkWanderer, yep. it all works as expected when I disable breaks at `EndOfStreamException`s.

**Comment by DarkWanderer** [comment]
@Treno1 FYI: Dapper в последней версии смёрджил поддержку массивов во входных параметрах (но пока не в результатах)

**Comment by DarkWanderer** [comment]
Array support is available in latest version as well, closing this (please open another issue if needed)
