### ISSUE TITLE
using stream for bulk copy

### ISSUE THREAD

**Issue by ahmeturun** [DarkWanderer/ClickHouse.Client#61]
Hi,
with current ClickHouseBulkCopy api it's not possible to use streams for bulk inserts. using ClickHouseBulkCopy's WriteToServerAsync method causes high memory consumption when the data to be copied is big(in my case inserting 20 million data with 5-6 columns causes high memory usage). It would be good to be able to use stream for bulk copy. this can be achieve by opening 'PostStreamAsync' of ClickHouseConnection to public api.

**Comment by DarkWanderer** [comment]
Hi,

Can you please provide more data about hight memory usage? What are your batching settings? What is the data structure?

I think I can expose `PostStreamAsync` without much issue, but I'd like to understand more about the problem

**Comment by DarkWanderer** [comment]
`PostStreamAsync` is now public, closing as no further info available
