### ISSUE TITLE
Add example for Dapper to the SQL-Parameters wiki page

### ISSUE THREAD

**Issue by barsv** [DarkWanderer/ClickHouse.Client#62]
I propose to add the following to the end of the https://github.com/DarkWanderer/ClickHouse.Client/wiki/SQL-Parameters page:

---- start of the change

### For Dapper

You need to pass parameters as Dictionary<string, object>.

For example, the following:
```
connection.QueryAsync<string>("select {p1:Int32}", new { p1 = 42 });
```
will not work. You need do it this way:
```
connection.QueryAsync<string>("select {p1:Int32}", 
    new Dictionary<string, object> { { "p1", 42 } });
```

---- end of the change

**Comment by barsv** [comment]
and one more change - replace the hyperlink https://clickhouse.tech/docs/ru/interfaces/cli/ with https://clickhouse.tech/docs/en/interfaces/cli/#cli-queries-with-parameters

**Comment by DarkWanderer** [comment]
Thanks for suggestions - added first note into "ORM" section and edited the URL.
