### ISSUE TITLE
Multi-statement queries not supported by HTTP interface

### ISSUE THREAD

**Issue by twittervideodev** [DarkWanderer/ClickHouse.Client#64]
Could you please provide some basic documentation and examples in the wiki?  I'm not using Visual Studio or an IDE with Intellisense, so it's difficult to know what I should be calling.  I've looked at other ClickHouse ADO connectors and yours looks to be the most promising, so it would be great to see it developed further.

I was expecting a standard ADO implementation with standard methods like ExecuteQuery, ExecuteNonQuery and ExecuteScalar (and maybe some DataReader and Fill methods). But based on the code, it looks like it only implements async methods (which means you need to modify the calling code to return Tasks in order to support await, etc. and this ripples through all the code.  Are you also planning to provide synchronous methods in the future?

The other problem I've noticed is that it's not possible to do multiple statements (e.g. multiple INSERTs in same command). I think this is because your ExecuteNonQueryAsync is calling PostSqlQueryAsync which returns HttpResponseMessage. I've read somewhere that multi statement queries aren't supported by the HTTP interface.  I need to be able to do multiple INSERTs to avoid errors like "DB::Exception: Too many parts (337). Merges are processing significantly slower than inserts."  Doing INSERTs one by one requires at least 7 to 10 ms forced delay between commands to avoid problems, so this creates a significant performance issue. My understanding is that these errors are caused by too many commands (and too frequently), which won't be a problem if multi-statement commands are supported.  So, I would be able to do 100,000 INSERTs in a single command without a problem (and much more quickly than 100,000 separate INSERTs).

Am I completely missing something obvious?  Thank you for any help you can provide (and thanks for your work on this very useful project).

**Comment by DarkWanderer** [comment]
Hi. To answer on the points:

1. The interface should fully support synchronous execution. Synchronous versions of the function [call `Async` under the hood and wait for the result](https://github.com/DarkWanderer/ClickHouse.Client/blob/master/ClickHouse.Client/ADO/ClickHouseCommand.cs#L84) (with all the necessary precautions against `SynchronizationContext`-related deadlocks). Do you have any specific code which does not work in synchronous scenario?
2. Multiple statements are not supported by ClickHouse itself, it's not `ClickHouse.Client` issue - you'll see same issues with other clients utilizing 'native' protocol
3. `too many parts` issues with multiple INSERTs are also not related to HTTP interface - it's related to the way ClickHouse processes inserted data. To insert multiple rows, you need to take a look [bulk insertion](https://github.com/DarkWanderer/ClickHouse.Client/wiki/Bulk-insertion) technique

**Comment by twittervideodev** [comment]
Thank you.  This was helpful.  Another issue I noticed is that the return value (int) from ExecuteNonQuery seems to always return 0.  In other ADO implementations, this returns the number of affected records (e.g. number of inserts, etc.).  Is this a bug?

Also, why is ExecuteScalar under the Connection object instead of Command?

**Comment by DarkWanderer** [comment]
> Thank you. This was helpful. Another issue I noticed is that the return value (int) from ExecuteNonQuery seems to always return 0. In other ADO implementations, this returns the number of affected records (e.g. number of inserts, etc.). Is this a bug?

Actually this particular small bit seems to be. I'll fix that

> Also, why is ExecuteScalar under the Connection object instead of Command?

It is not. `ExecuteStatementAsync`, `ExecuteScalarAsync`, `ExecuteReaderAsync`, `ExecuteDataTable` are [extensions](https://github.com/DarkWanderer/ClickHouse.Client/blob/master/ClickHouse.Client/Utility/ConnectionExtensions.cs) for  `Connection` class, not parts of the API itself. You can choose to not use them

**Comment by DarkWanderer** [comment]
Closing as all questions seem to be answered
