### ISSUE TITLE
datetime incorrect on none utc time zone

### ISSUE THREAD

**Issue by mbtolou** [DarkWanderer/ClickHouse.Client#67]
dapper
datetime incorrect on none utc time zone

**Comment by DarkWanderer** [comment]
Could you please provide a minimal example?

**Comment by mbtolou** [comment]
```csharp
using ClickHouse.Client.ADO;
using Dapper;


var connection = GetClickHouseConnection("test");

connection.Execute(@"drop table if exists test.test_timezone");

connection.Execute(@"CREATE TABLE test.test_timezone
                    (
                        `clock` DateTime('Asia/Tehran'),
                        `clock_utc` DateTime,
                        `message` String
                    )
                    ENGINE = MergeTree
                    PARTITION BY toYYYYMM(clock)
                    ORDER BY (clock);");

connection.Execute(@"INSERT INTO test.test_timezone (clock,clock_utc, message) VALUES('2021-01-01 01:01:01','2021-01-01 01:01:01', '2021-01-01 01:01:01')");

var data = connection.Query(@"SELECT * from test.test_timezone").ToList();

Console.WriteLine($"Select clock : {data[0].clock.ToString()} utc:{data[0].clock_utc.ToString()}");

data = connection.Query(@"SELECT toString(clock,'Asia/Tehran') as clock ,clock_utc from test.test_timezone").ToList();

Console.WriteLine($"Selected string clock : {data[0].clock.ToString()} utc:{data[0].clock_utc.ToString()}");
```


result :

Select clock : 12/31/2020 9:31:01 PM utc:12/31/2020 9:31:01 PM
Selected string clock : 2021-01-01 01:01:01 utc:12/31/2020 9:31:01 PM

**Comment by DarkWanderer** [comment]
1. what is the value of `data[0].clock_utc.Kind`?
2. what does `select timezone()` query output?

**Comment by mbtolou** [comment]
select timezone()
is
'Asia/Tehran'


my result with dbeaver is correct :

![image](https://user-images.githubusercontent.com/6413705/106378336-1ce80780-63b9-11eb-9570-237a3ab46226.png)

**Comment by DarkWanderer** [comment]
Ok, so you actually expect same values in both columns. I had asked this for a reason:

> what is the value of data[0].clock_utc.Kind?

* In C#, UTC values are loaded by default. So when you do `clock.ToString()`, it prints UTC time by default, unless goaded with `ToLocalTime()`
* DBeaver shows the time in the column timezone and **does not specify in which**

You have assumed that `clock_utc` column would be in UTC, but it is not. Since server has a non-UTC timezone, In your table:
```
CREATE TABLE test.test_timezone
                    (
                        `clock` DateTime('Asia/Tehran'),
                        `clock_utc` DateTime,
                        `message` String
                    )
```
both columns are actually in Tehran time. So when inserting into both columns, you are actually inserting `12/31/2020 9:31:01` UTC, which is `2021-01-01 01:01:01` Tehran time. So the client correctly tells you that time in UTC.

Try explicitly specifying column timezone:
```
CREATE TABLE test.test_timezone
                    (
                        `clock` DateTime('Asia/Tehran'),
                        `clock_utc` DateTime('Etc/UTC'),
                        `message` String
                    )
```
and pay attention to `DateTime.Kind` property

**Comment by mbtolou** [comment]
`clock` is big problem

`clock_utc` work correctly

driver not detect time zone of column

**Comment by DarkWanderer** [comment]
If you take `clock.ToLocalTime()` - does the value look correct to you?

**Comment by mbtolou** [comment]
I am test 

```
DateTime.Now
DateTime.UtcNow
DateTime.Now.ToLocalTime()
DateTime.Now.ToUniversalTime()
```

all of this has problem with datetime

only worked item 

`csharp
DateTime.SpecifyKind(DateTime.Now, DateTimeKind.Utc)
`

**Comment by mbtolou** [comment]
![image](https://user-images.githubusercontent.com/6413705/106389284-cc43cf00-63f7-11eb-9130-7cff72435f8b.png)

dbeaver clickhouse config

**Comment by mbtolou** [comment]
> If you change column type to `DateTime('Asia/Tehran')` and take `clock.ToLocalTime()` - does the value look correct to you?

with this method datetime work correctly.
but i am using dapper with dynamic list and multiple values

**Comment by DarkWanderer** [comment]
If you need to operate on local times exclusively, I can suggest adding a handler to Dapper's `SqlMapper`
```
public class LocalDateTimeHandler : SqlMapper.TypeHandler<DateTime>
{
    public override void SetValue(IDbDataParameter parameter, DateTime value)
    {
        parameter.Value = value.ToUniversalTime();
    }

    public override DateTime Parse(object value)
    {
        return ((DateTime)value).ToLocalTime();
    }
}
```
Then:
```
SqlMapper.AddTypeHandler(new LocalDateTimeHandler());
```
This way all timestamps will be converted to local time when read, but you still could convert them to UTC if needed

**Comment by mbtolou** [comment]
SqlMapper.AddTypeHandler(new LocalDateTimeHandler());

not worked
can you write minimal example

**Comment by mbtolou** [comment]
can you create unsupported exception for none UTC DateTime format when write data?

**Comment by mbtolou** [comment]
https://github.com/DarkWanderer/ClickHouse.Client/pull/68

**Comment by DarkWanderer** [comment]
Below is an example of adding a handler which will output all dates/times in local timezone ('Asia/Tehran' in your case). This does not break correctness of timestamps (i.e. `ToUniversalTime`/`ToLocalTime` will still return correct values). To get `DateTimeOffset`, unfortunately at the moment you would need to use `ClickHouseDataReader.GetDateTimeOffset` method directly, bypassing Dapper.

I agree that idea to read/store `DateTimeOffset` directly has merit, but I cannot change it right now as it will break backward compatibility for a lot of users. I may add this in next major version.

```
using System;
using System.Data;
using ClickHouse.Client.ADO;
using Dapper;

namespace clickhouse.dapper
{
    class Program
    {
        static void Main(string[] args)
        {
            using var connection = new ClickHouseConnection("Host=lenovo.local");

            SqlMapper.AddTypeHandler(new LocalDateTimeHandler());
            
            PrintValue(connection.QuerySingle<DateTime>("SELECT toDateTime('2020-01-01 01:01:01', 'Asia/Tehran')"));
        }

        private static void PrintValue(object value)
        {
            if (value is DateTime dt)
                PrintDateTime(dt);
            else
            Console.WriteLine("Type: {0}, value: {1}", value.GetType().Name, value);
        }

        private static void PrintDateTime(DateTime value)
        {
            Console.WriteLine("Type: {0}, value: {1}", value.Kind, value);
        }

        public class LocalDateTimeHandler : SqlMapper.TypeHandler<DateTime>
        {
            public override void SetValue(IDbDataParameter parameter, DateTime value)
            {
                parameter.Value = value.ToUniversalTime();
            }

            public override DateTime Parse(object value)
            {
                return ((DateTime)value).ToLocalTime();
            }
        }
    }
}
```

**Comment by mbtolou** [comment]
with this:

`PrintValue(connection.Query("SELECT toDateTime('2020-01-01 01:01:01', 'Asia/Tehran')"));`

not working

**Comment by mbtolou** [comment]
> #68

why not accept with this pull request ?
