### ISSUE TITLE
The ClickHouseBulkCopy disposes the underlying database connection

### ISSUE THREAD

**Issue by chjahnert** [DarkWanderer/ClickHouse.Client#78]
The `ClickHouseBulkCopy` disposes the underlying database connection even though it received it as a dependency through the constructor. Types should only dispose objects that they have created them selves. After disposing the `ClickHouseBulkCopy`, we would expect the passed in `ClickHouseConnection` object to be in tact.

```
    using (ClickHouseConnection connection = new ClickHouseConnection(CONNECTION_STRING))
    {
        connection.Open();

        using (ClickHouseBulkCopy operation = new ClickHouseBulkCopy(connection))
        {
            operation.DestinationTableName = "table";

            await operation.WriteToServerAsync(batch);
        }

        // The database connection object should be in tact at this point, but it was disposed
        // when the ClickHouseBulkCopy object was disposed.
    }
```

Also, when creating a new object, the object's state should be valid and ready to be used after the constructor completes. The constructor should accept all parameters required to initialize an object. The `ClickHouseBulkCopy` requires the destination table name, but does not require it to be passed to the constructor, hence the instance constructed is not usable as is. It requires additional initialization steps that are not obvious to the consumers of the API.

**Comment by DarkWanderer** [comment]
Hi,

`DestinationTableName` field of `ClickHouseBulkCopy` was intentionally done to mimic `SqlBulkCopy` (see [docs](https://docs.microsoft.com/ru-ru/dotnet/api/system.data.sqlclient.sqlbulkcopy?view=dotnet-plat-ext-5.0))

Disposing the connection is however not needed indeed, I can correct that
