### ISSUE TITLE
Exception thrown: 'System.IO.EndOfStreamException' 

### ISSUE THREAD

**Issue by mbtolou** [DarkWanderer/ClickHouse.Client#88]
Hi.

Exception has occurred: CLR/System.IO.EndOfStreamException
Exception thrown: 'System.IO.EndOfStreamException' in System.Private.CoreLib.dll: 'Unable to read beyond the end of the stream.'
   at System.IO.BinaryReader.ReadByte()
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at ClickHouse.Client.Formats.ExtendedBinaryReader.Read7BitEncodedInt() in ClickHouse.Client\Formats\ExtendedBinaryReader.cs:line 16

**Comment by DarkWanderer** [comment]
Can you give me a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example) of how to reproduce this?

**Comment by DarkWanderer** [comment]
Can you give me a [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example) of how to reproduce this?

**Comment by mbtolou** [comment]
after update driver solved 
thanks
