### ISSUE TITLE
Add clearer exception when C# decimal value too big / small on insert

### ISSUE THREAD

**Issue by nrenzoni** [DarkWanderer/ClickHouse.Client#89]
Hi,

When inserting into a table with a C# valued object of type `decimal`  greater than the supported value of the `Decimal` type in a given Clickhouse table, the code throws an unclear exception of type `OverflowException` with the message `System.OverflowException: Value was either too large or too small for an Int64`. The code fails in class `BinaryStreamWriter` in function `Write(DecimalType decimalType, object value)`, with the top function in the stack trace `System.Decimal.ToInt64(Decimal d)`. 

In my case, inserting an object `var d = new decimal(5500000000)` into a clickhouse table defined as: `create table test.t1 (c1 Decimal(18,10)) engine = Memory()`, will throw the above exception.

1) I think it would be easier for developers to throw a ClickhouseClient exception with an explicit message that the value is out of range of the clickhouse column type (can do this by surrounding the code with a try /catch in `Write(DecimalType decimalType, object value)`). 

2) Is there an already existing way to verify if my C# decimal variable is out of range for a given Clickhouse Decimal type? Like even before doing the insert, I would like to verify if the decimal I received in my code logic is out of range before attempting to save to clickhouse. If not, maybe creating / adding to an existing class a `ClickhouseTypeInRangeVerifier` would be appropriate. 

Many thanks!

**Comment by DarkWanderer** [comment]
Exception was added, range check is something which I would consider separately
