### ISSUE TITLE
Working with non utc datetime

### ISSUE THREAD

**Issue by RZProf** [DarkWanderer/ClickHouse.Client#91]
When writing a query over clickhouse database the client apply ToUniversal method on date time objects. How i can ignore universal conversion and read actual value of stored date time?!

best regards!

**Comment by DarkWanderer** [comment]
Hi,

ClickHouse actually stores UTC DateTime internally. To get a local time, you can either:

- Use `DateTime.ToLocalTime` method to get datetime in your local timezone
- Use `GetDateTimeOffset` method of `DbDataReader` and then use `DateTimeOffset.DateTime` property to get DateTime in source column timezone

**Comment by DarkWanderer** [comment]
Since version 4.0.0.456, the client will now convert DateTime into required timezone. Please check if that covers your use case
