### ISSUE TITLE
Return `query_id` with the results

### ISSUE THREAD

**Issue by OmarBazaraa** [DarkWanderer/ClickHouse.Client#96]
Hi,

We would like to retrieve the `query_id` with the results of our issued queries to be able to further track and investigate failures and high latency queries.

Can you please provide this feature?

Thanks

**Comment by DarkWanderer** [comment]
Hi. I plan to add `QueryId` property to `ClickHouseCommand` as part of #79, I see no issues backfilling it from headers if it's not set manually

**Comment by OmarBazaraa** [comment]
This will be great. Looking forward to seeing this soon.
Thanks @DarkWanderer :)

**Comment by OmarBazaraa** [comment]
Any updates on this feature, @DarkWanderer?

**Comment by DarkWanderer** [comment]
Hi - no updates yet, I should get my hands on it soon ™️

**Comment by DarkWanderer** [comment]
Released in [4.2.0](https://github.com/DarkWanderer/ClickHouse.Client/releases/tag/4.2.0)
